before:
  hooks:
    - go mod download

builds:
  - id: goproxy
    main: ./cmd/goproxy
    ldflags:
      - -s -w -X github.com/goproxy/goproxy/cmd/goproxy/internal.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - linux_ppc64le
      - linux_s390x
      - windows_386
      - windows_amd64
      - windows_arm64
    mod_timestamp: "{{.CommitTimestamp}}"

archives:
  - id: goproxy

dockers:
  - goarch: "386"
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-386
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-386
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-386
      - ghcr.io/goproxy/goproxy:{{.Major}}-386
      - ghcr.io/goproxy/goproxy:latest-386
    use: buildx
    build_flag_templates:
      - --platform=linux/386
    extra_files:
      - ./
  - goarch: amd64
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-amd64
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-amd64
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-amd64
      - ghcr.io/goproxy/goproxy:{{.Major}}-amd64
      - ghcr.io/goproxy/goproxy:latest-amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - ./
  - goarch: arm64
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-arm64
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-arm64
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-arm64
      - ghcr.io/goproxy/goproxy:{{.Major}}-arm64
      - ghcr.io/goproxy/goproxy:latest-arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
    extra_files:
      - ./
  - goarch: arm
    goarm: "6"
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-armv6
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-armv6
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-armv6
      - ghcr.io/goproxy/goproxy:{{.Major}}-armv6
      - ghcr.io/goproxy/goproxy:latest-armv6
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
    extra_files:
      - ./
  - goarch: arm
    goarm: "7"
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-armv7
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-armv7
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-armv7
      - ghcr.io/goproxy/goproxy:{{.Major}}-armv7
      - ghcr.io/goproxy/goproxy:latest-armv7
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
    extra_files:
      - ./
  - goarch: ppc64le
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-ppc64le
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-ppc64le
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-ppc64le
      - ghcr.io/goproxy/goproxy:{{.Major}}-ppc64le
      - ghcr.io/goproxy/goproxy:latest-ppc64le
    use: buildx
    build_flag_templates:
      - --platform=linux/ppc64le
    extra_files:
      - ./
  - goarch: s390x
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-s390x
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-s390x
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-s390x
      - ghcr.io/goproxy/goproxy:{{.Major}}-s390x
      - ghcr.io/goproxy/goproxy:latest-s390x
    use: buildx
    build_flag_templates:
      - --platform=linux/s390x
    extra_files:
      - ./

docker_manifests:
  - name_template: ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}
    image_templates:
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-386
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-amd64
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-arm64
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-armv6
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-armv7
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-pc64le
      - ghcr.io/goproxy/goproxy:sha-{{.ShortCommit}}-s390x
  - name_template: ghcr.io/goproxy/goproxy:{{.RawVersion}}
    image_templates:
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-386
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-amd64
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-arm64
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-armv6
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-armv7
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-pc64le
      - ghcr.io/goproxy/goproxy:{{.RawVersion}}-s390x
  - name_template: ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}
    image_templates:
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-386
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-amd64
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-arm64
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-armv6
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-armv7
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-pc64le
      - ghcr.io/goproxy/goproxy:{{.Major}}.{{.Minor}}-s390x
  - name_template: ghcr.io/goproxy/goproxy:{{.Major}}
    image_templates:
      - ghcr.io/goproxy/goproxy:{{.Major}}-386
      - ghcr.io/goproxy/goproxy:{{.Major}}-amd64
      - ghcr.io/goproxy/goproxy:{{.Major}}-arm64
      - ghcr.io/goproxy/goproxy:{{.Major}}-armv6
      - ghcr.io/goproxy/goproxy:{{.Major}}-armv7
      - ghcr.io/goproxy/goproxy:{{.Major}}-pc64le
      - ghcr.io/goproxy/goproxy:{{.Major}}-s390x
  - name_template: ghcr.io/goproxy/goproxy:latest
    image_templates:
      - ghcr.io/goproxy/goproxy:latest-386
      - ghcr.io/goproxy/goproxy:latest-amd64
      - ghcr.io/goproxy/goproxy:latest-arm64
      - ghcr.io/goproxy/goproxy:latest-armv6
      - ghcr.io/goproxy/goproxy:latest-armv7
      - ghcr.io/goproxy/goproxy:latest-pc64le
      - ghcr.io/goproxy/goproxy:latest-s390x

snapshot:
  name_template: '{{trimprefix .Summary "v"}}'
