before:
  hooks:
    - go mod download

builds:
  - id: goproxy
    main: ./cmd/goproxy
    ldflags:
      - -s -w -X github.com/goproxy/goproxy/cmd/goproxy/internal.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - linux_ppc64le
      - linux_s390x
      - windows_386
      - windows_amd64
      - windows_arm64
    mod_timestamp: "{{.CommitTimestamp}}"

archives:
  - id: default
